# Пользователи

## Найти пользователя по email

POST http://127.0.0.1:3102/users/index HTTP/1.1
content-type: application/json

{
    "email": "davie-jones@fakemail.com"
}

###

## Создать нового пользователя

POST http://127.0.0.1:3102/users HTTP/1.1
content-type: application/json

{
    "name": "Davie Jones",
    "email": "davie-jones@fakemail.com",
    "userRang": "PRO",
    "password": "releasekrakn"
}

###

## Отправка аватарки пользователю

POST http://127.0.0.1:3102/users/64929f0867a6070e465098cd/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /home/jason_doe/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
