#Предложения

##Получить список комментариев по индентификатору предложения

GET  http://127.0.0.1:3102/comments/64929f0867a6070e465098cf HTTP/1.1
content-type: application/json

###

##Создать комментарий

POST  http://127.0.0.1:3102/comments HTTP/1.1
content-type: application/json

{
  "offerId": "648e3ddbdf519f968f00fc01",
  "textContent": "A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.",
  "rate": 3
}

###


