#Предложения

##Получить список предложений

GET  http://127.0.0.1:3102/offers?limit=60 HTTP/1.1
content-type: application/json

###

##Создать предложение

POST http://127.0.0.1:3102/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmllLWpvbmVzQGZha2VtYWlsLmNvbSIsImlkIjoiNjQ5NDJiNzU1Yjc3ZDNhZTgwMGJjYmVhIiwiaWF0IjoxNjg3NDM4ODM5LCJleHAiOjE2ODc0Mzk3Mzl9.TBK_GNWMkDd8htcIiBsog5axMUPZ5RA8SC-VLDUrXds
content-type: application/json

{
    "title": "Amazing and Extremely Central Flat!!!",
    "userId": "648c28c563fbbf6a409fb84a",
    "description": "A quiet cozy and picturesque .",
    "city": "Paris",
    "previewImageSrc": "img/10.png",
    "offerImageSrc": ["img/10.png", "img/11.png", "img/12.png", "img/13.png", "img/14.png", "img/15.png"],
    "isPremium": true,
    "estateType": "hotel",
    "roomsQuantity": 4,
    "guestQuantity": 6,
    "price": 50000,
    "goods": ["Washer", "Towels", "Fridge"],
    "location": {"latitude": 52.770216, "longitude": 5.595168}
}

###

##Обновить данные предложения

PATCH http://127.0.0.1:3102/offers/649415be59f21ae541f9ace2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmllLWpvbmVzQGZha2VtYWlsLmNvbSIsImlkIjoiNjQ5NDJiNzU1Yjc3ZDNhZTgwMGJjYmVhIiwiaWF0IjoxNjg3NDM4ODM5LCJleHAiOjE2ODc0Mzk3Mzl9.TBK_GNWMkDd8htcIiBsog5axMUPZ5RA8SC-VLDUrXds
content-type: application/json

{
    "description": "A quiet cozy and picturesque that hides behind a a river by the unique lightness of A."
}

###

##Запросить детальную информацию о предложении

GET http://localhost:3102/offers/6493dc28acbc42f796eafdee HTTP/1.1

###

##Удалить информацию о предложении

DELETE  http://localhost:3102/offers/648d8d9d0e2eeeb17c393da6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmllLWpvbmVzQGZha2VtYWlsLmNvbSIsImlkIjoiNjQ5M2Y1MzAzZWU4NmY0OTExZjFhNGMwIiwiaWF0IjoxNjg3NDE4MTcyLCJleHAiOjE2ODc0MTkwNzJ9.sY2O2NShnXjo83fiT-hCVLveR6Vea9sH31UxGAm7sKw

###


