#Предложения

##Получить список предложений

GET  http://127.0.0.1:3102/offers?limit=5 HTTP/1.1
content-type: application/json

###

##Создать предложение

POST http://127.0.0.1:3102/offers HTTP/1.1
content-type: application/json

{
    "title": "Amazing and Extremely Central Flat!!!",
    "userId": "648c28c563fbbf6a409fb84a",
    "description": "A quiet cozy and picturesque .",
    "city": "Pariss",
    "previewImageSrc": "img/10.png",
    "offerImageSrc": ["img/10.png", "img/11.png", "img/12.png", "img/13.png", "img/14.png", "img/15.png"],
    "isPremium": true,
    "estateType": "hotel",
    "roomsQuantity": 4,
    "guestQuantity": 6.3,
    "price": 50000,
    "goods": ["Washer", "Towels", "Fridge"],
    "location": {"latitude": 52.770216, "longitude": 5.595168}
}

###

##Обновить данные предложения

PATCH http://127.0.0.1:3102/offers/648e295a0baa53f55d078d30 HTTP/1.1
content-type: application/json

{
    "description": "A quiet cozy and picturesque that hides behind a a river by the unique lightness of A."
}

###

##Запросить детальную информацию о предложении

GET http://localhost:3102/offers/648f761c489983811ae01dd9 HTTP/1.1

###

##Удалить информацию о предложении

DELETE  http://localhost:3102/offers/648d8d9d0e2eeeb17c393da6 HTTP/1.1

###


