export const MINIMUM_OFFER_TITLE_LENGTH = 10;
export const MAXIMUM_OFFER_TITLE_LENGTH = 100;

export const MINIMUM_OFFER_DESC_LENGTH = 20;
export const MAXIMUM_OFFER_DESC_LENGTH = 1024;

export const OFFER_PREVIEW_IMAGE_QUANTITY = 6;

export const MINIMUM_OFFER_ROOM_QUANTITY = 1;
export const MAXIMUM_OFFER_ROOM_QUANTITY = 8;

export const MINIMUM_OFFER_GUEST_QUANTITY = 1;
export const MAXIMUM_OFFER_GUEST_QUANTITY = 10;

export const MINIMUM_OFFER_PRICE = 100;
export const MAXIMUM_OFFER_PRICE = 100000;

export const DEFAULT_OFFER_LIST_LIMIT = 60;

export const DEFAULT_OFFER_COMMENT_QUANTITY = 0;

export const DEFAULT_OFFER_RATE = 0;

